### ISSUE TITLE
Fullstack Capstone Project

### ISSUE THREAD

**Issue by Graycemuthui** [Graycemuthui/Book-a-dev#24]
Hello, In this project we are 5.
@SaidRasinlic 
@MICHAELMUNAVU83 
@Graycemuthui 
@assadounto 
@CrystallineButterfly 

Here is a link to the repo [link](https://github.com/Graycemuthui/Book-a-dev)
Here is a link to the Kanban Board [link](https://github.com/users/Graycemuthui/projects/2)

### Screenshot
![book a dev](https://user-images.githubusercontent.com/95374858/199250803-7c991b75-2194-4ccd-b3e2-61406bdfac80.jpg)

### Changes made
- Equalized on the tasks.
- Add descriptions to all

**Comment by Meltrust** [comment]
Hi @Graycemuthui,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, and points assignments are more equal.✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
